### ISSUE TITLE
🐰 Development documentation

### ISSUE THREAD

**Issue by k33g** [mklabs/tilt#3]
Please @mklabs  can you add a "development" section in the README file? (for newbie 👶 )

e.g.: 
- `npm-watch` isn't in `package.json`, 
- launch `npm run babel`
- what to do to run the project? (how to run transpiler?)
- ...

In other words: how can I start to code ❓

**Comment by mklabs** [comment]
oops :confused: 

yep, I'll do. Thank you for the feedback. Will probably continue working on it tonight, if you want to join me i'll probably stream it.

so to answer quickly:

examples/ directory is what I used to test the lib

```
git clone https://github.com/mklabs/tilt
cd tilt && npm install
cd examples
node index.js
```

You can also use `npm start`, it'll use nodemon to start the server which is quite convenient.

PS: You're not a :baby: anymore!

**Comment by mklabs** [comment]
You may need to run `npm run babel` before.

I'll rework the build thing to use a Makefile, should be simpler.

**Comment by mklabs** [comment]
`npm run watch` uses github.com/mklabs/watchd as well

forgot to include it in package.json

```
npm install mklabs/watchd -D
npm run watch
```

**Comment by k33g** [comment]
nice, I'll review it quickly ... after 🍖

**Comment by mklabs** [comment]
Good :meat_on_bone: and :poultry_leg:

**Comment by k33g** [comment]
thx,
 in fact, I've already try

```
git clone https://github.com/mklabs/tilt
cd tilt && npm install
cd examples
node index.js
```

but I get this

```
/Users/k33g/dev.works/tilt/src/tilt.js:8
class Tilt {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/k33g/dev.works/tilt/index.js:3:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

I try with `npm run watch`

```
> tilt@1.0.0 watch /Users/k33g/dev.works/tilt
> watchd lib/* examples/**.js test/**.js -c 'npm run babel' -c 'npm test'

Watchd listen on localhost:31415
undefined:1
GET / HTTP/1.1
^

SyntaxError: Unexpected token G
    at Object.parse (native)
    at Socket.<anonymous> (/Users/k33g/dev.works/tilt/node_modules/node-watchd/lib/watchd.js:56:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/k33g/.nvm/versions/node/v5.10.1/bin/node" "/Users/k33g/.nvm/versions/node/v5.10.1/bin/npm" "run" "watch"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! tilt@1.0.0 watch: `watchd lib/* examples/**.js test/**.js -c 'npm run babel' -c 'npm test'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tilt@1.0.0 watch script 'watchd lib/* examples/**.js test/**.js -c 'npm run babel' -c 'npm test''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     watchd lib/* examples/**.js test/**.js -c 'npm run babel' -c 'npm test'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/k33g/dev.works/tilt/npm-debug.log
```

I upgrade my node version to 6.2.0, same problem with `npm run watch`

and now with `cd exemples` then `node index.js` I get:

```
C02R91V6G8WM:tilt k33g$ cd examples/
C02R91V6G8WM:examples k33g$ node index.js 
module.js:442
    throw err;
    ^

Error: Cannot find module 'classy-router'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (router.js:3:20)
    at Module._compile (module.js:541:32)
    at loader (/Users/k33g/dev.works/tilt/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/k33g/dev.works/tilt/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

```

same error with `npm start`

**Comment by mklabs** [comment]
wrong dependency with watchd, let me 5 minute. I'll push a commit to fix the package.json file so that you just have to run npm start.

**Comment by mklabs** [comment]
edfd8995acc0a4f7f0c159380df746933c8b59fa should help

I'll update the readme.
- `npm run start` to start the server. I'll run babel once before.
- `npm run watch` will recompile and relaunch the tests.
