### ISSUE TITLE
Class constructor Router cannot be invoked without 'new'

### ISSUE THREAD

**Issue by k33g** [mklabs/tilt#4]
after `npm run start` I call [http://localhost:3000](http://localhost:3000) and I get that error:

```
/Users/k33g/dev.works/tilt/lib/router.js:21
    return _possibleConstructorReturn(this, Object.getPrototypeOf(Router).call(this, options));
                                                                          ^

TypeError: Class constructor Router cannot be invoked without 'new'
    at Router (router.js:7:24)
    at new Router (/Users/k33g/dev.works/tilt/examples/vertical/app/controllers/main.js:19:75)
    at /Users/k33g/dev.works/tilt/src/tilt.js:59:28
    at Array.forEach (native)
    at Server.<anonymous> (/Users/k33g/dev.works/tilt/src/tilt.js:58:17)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:543:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
```

**Comment by mklabs** [comment]
that's weird, never got that error

**Comment by mklabs** [comment]
just got it now .. : d

**Comment by mklabs** [comment]
weird, got it fixed without doing anything.

Try

```
rm -rf src/
npm run babel
npm start
```

**Comment by mklabs** [comment]
no still here, even with the tests. Let me fix it. I'll let you know when it's good to go.

**Comment by mklabs** [comment]
http://stackoverflow.com/questions/32981988/class-constructors-cannot-be-invoked-without-new

Apparently, babel transpiled class (tilt source) cannot be used to extend regular ES6 class (examples)

**Comment by mklabs** [comment]
Should be ok now.
