### ISSUE TITLE
Cannot find module 'tilt-react-views'

### ISSUE THREAD

**Issue by k33g** [mklabs/tilt#5]
After launch `npm run start`:

```
module.js:442
    throw err;
    ^

Error: Cannot find module 'tilt-react-views'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k33g/dev.works/tilt/lib/tilt.js:7:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

```

**Comment by mklabs** [comment]
`>_<`

Let me check. Should be https://github.com/mklabs/tilt-react-views

**Comment by mklabs** [comment]
Shouldn't be the case: https://github.com/k33g/tilt/blob/master/package.json#L15

Did you try rerunning `npm install` ?

**Comment by k33g** [comment]
oups my bad, you're right, it's better, but I get an other 🐛 now, when I try [http://localhost:3000/](http://localhost:3000/) _I assume it's te default port_, I get this:

**in the browser:**

```
Error: View index not found
   at Promise (/Users/k33g/dev.sandbox/tilt/node_modules/tilt-react-views/index.js:64:33)
   at ReactViews.view (/Users/k33g/dev.sandbox/tilt/node_modules/tilt-react-views/index.js:59:12)
   at ReactViews.render (/Users/k33g/dev.sandbox/tilt/node_modules/tilt-react-views/index.js:47:17)
   at Router.index (/Users/k33g/dev.sandbox/tilt/examples/vertical/app/controllers/main.js:12:16)
   at Router.dispatch (/Users/k33g/dev.sandbox/tilt/node_modules/tilt-router/lib/index.js:94:19)
   at _controllers.forEach (/Users/k33g/dev.sandbox/tilt/lib/tilt.js:68:20)
   at Array.forEach (native)
   at Server.http.createServer (/Users/k33g/dev.sandbox/tilt/lib/tilt.js:62:25)
   at emitTwo (events.js:106:13)
   at Server.emit (events.js:191:7)
```

**and in the console:**

```
  tilt Starting server +0ms
  tilt Loading controller: /Users/k33g/dev.sandbox/tilt/examples/vertical/app/controllers/main.js +16ms
  tilt Loading controller: /Users/k33g/dev.sandbox/tilt/examples/vertical/app/controllers/profile.js +2ms
  tilt Views dirs  (Pattern: app/views/) +2ms
Server started
  tilt Incoming request +8s /
_http_outgoing.js:346
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at Array.write (/Users/k33g/dev.sandbox/tilt/node_modules/finalhandler/index.js:126:9)
    at listener (/Users/k33g/dev.sandbox/tilt/node_modules/on-finished/index.js:169:15)
    at onFinish (/Users/k33g/dev.sandbox/tilt/node_modules/on-finished/index.js:100:5)
    at callback (/Users/k33g/dev.sandbox/tilt/node_modules/ee-first/index.js:55:10)
    at IncomingMessage.onevent (/Users/k33g/dev.sandbox/tilt/node_modules/ee-first/index.js:93:5)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by mklabs** [comment]
nasty error :/

The fwk doesn't find the default views directory, forgot to update the examples.

You can do so with:

```
tilt.views(path.join(__dirname, 'app/views/'));
```

in examples/vertical/index.js

**Comment by k33g** [comment]
@mklabs great it works 👍

**Comment by mklabs** [comment]
Ty for the report, fixed a nasty bug with react-views.
